name: Generate GitHub Stats SVG

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download GitHub stats SVG
        run: |
          curl -L -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=dainyjose&show_icons=true&theme=tokyonight&hide_border=true&include_all_commits=true&count_private=true"

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-stats.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push
